version: '3.4'

services:
  app:
    build: .
    container_name: news-app
    environment:
      CONFIG: "news-app/config.yaml"
      POSTGRES_DB: news-app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    image: "postgres:10.20-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: news-app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql